### PR TITLE
Set 'max-len' to 120

### PR DESCRIPTION
**Pull request by zimbatm**
Set 'max-len' to 120

### CODE REVIEW

**Comment by zimbatm** [comment]
What's the reasoning behind this @srounce ?

**Comment by srounce** [comment]
200 is a crazy long length. IMO if this is going to be a rule, it might as well have a sensible setting. I pushed for 80, but 120 was seen as a happy in-between.

**Comment by colinclarkbcgdv** [comment]
What changes need to be made to each repo?

/frontend seems to work with this new rule fyi

**Comment by zimbatm** [comment]
Feel free to re-open one if you want to pursue this @srounce

**Pull request closed without merging**
