### PR TITLE
Disabled 'default-case' in switch statement requirement

### PR DESCRIPTION
**Pull request by srounce**
I know peeps didn't agree, but I'd like to discuss further.
My gripe is that this rule occasionally leads to switches like:
```javascript
const { type, payload } = request;
let response = {
    request,
    type: UNKNOWN_ACTION
};

switch(type) {
    case FOO:
        response = Actions.foo(response);
        break;
    case BAR:
        response = Actions.bar(response);
        break;
    case BAZ:
        response = Actions.baz(response);
        break;
   default:
});

response.timestamp = new Date();

send(response);

return;
```

Note the use of `default`, not serving any real purpose but arbitrarily satisfying the linting rules.

### CODE REVIEW

**Comment by colinclarkbcgdv** [comment]
```
const { payload } = message;

switch(type) {
    case FOO:
        return doStuff();
    case BAR:
        return doOtherStuff();
    case BAZ:
        payload.name = payload.name.trim()
        break
    default:
        return doSomethingElse(payload);
}

```

i vote we stick to the standards. `default` cases are used in many languages for the very purpose of handling drop-through cases, and the linter helps maintain those standards

**Comment by eadz** [comment]
```javascript
const { payload } = message;

switch(type) {
    case FOO:
        return doStuff();
    case BAR:
        return doOtherStuff();
    case BAZ:
        payload.name = payload.name.trim()
        break
    default:
       throw 'what the hell are you sending to this function';
}
```

**Comment by srounce** [comment]
> i vote we stick to the standards...

I'm not aware of any language where default cases in switches are required as standard.

From ECMA262 spec:
> *DefaultClause* : `default` : *StatementList*<sub>opt</sub>
> 1. If the StatementList is present, return ContainsDuplicateLabels of StatementList with argument labelSet.
> 2. Else return false.

Note the <sub>opt</sub>ional tag.

Original example probably not the best, see updated.

**Comment by colinclarkbcgdv** [comment]
I am still not convinced that this is a good idea. The pros of having a linter remind a developer of the usefulness of using a default _when they may have forgotten to use one_ outweighs the con you find in having an empty default case in some instances. How many will this really affect anyway? Also, add a code comment to the empty default case to ensure the reasons for it are documented.

**Comment by eadz** [comment]
The linter doesn't remind you of the "need of" a default case, the default
case isn't required ( bar a linter requirement, but then that would be
recursion)

The purpose of the lint rule is to make sure you don't *forget* about a
default case should one be required. Whether you add a blank empty default
case, or a comment to show that you didn't forget, the same goal is
achieved.

Note this rule is really on the edge, what's next, a required else
statement in an if block to make sure you didn't forget the "else" option?

I think the comment rule is a good compromise, and meets the *purpose* of
the lint rule.


-- 
Eaden McKee

**Comment by colinclarkbcgdv** [comment]
For clarity, I was not saying a default case is required. Amended comment above.

**Comment by zimbatm** [comment]
One option is to spend all our time discussing the ESlint rules. That will ensure that no bug is ever written :-p

**Comment by eadz** [comment]
discussed offline, going with the comment rule. 

you can add a default case, or a comment to pass the rule.

**Comment by srounce** [comment]
Changed to comment matching: all of the following are valid:
```
No default: 
No default: blah blah
no default:blahblah
No default blahblah
No default:blahblah
NO DEFAULT:blahblah
No default because blah blah
```

**Review by eadz — APPROVED** [review]
time to move on!

**Review by zimbatm — APPROVED** [review]

**Pull request merged**
